using DevExpress.Utils;
using SKLAD.EF;
using SKLAD.MODEL;
using SKLAD.SERVICE;
using SKLAD.VIEWS.Tools;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace SKLAD.VIEWS.Controls
{
    public partial class Mahsulotlar_Kirim : UserControl
    {
        public Mahsulotlar_Kirim()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SKLAD.EF.EFcontext dbContext = new SKLAD.EF.EFcontext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Event.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                pivotGridControl1.DataSource = dbContext.Event.AsNoTracking().ToList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());

            using (var db = new EFcontext())
            {
                lookUpEdit1.Properties.DataSource = db.ReportLayout.Where(o => o.Type == ReportLayout.ReportLayoutType.Incoming).AsNoTracking().ToList();
            }

        }

        private void saqlash_Click(object sender, System.EventArgs e)
        {
            var form = new InfoRequestForm();
            form.ShowDialog();
            if (!string.IsNullOrEmpty(form.name))
            {
                var layout = new MemoryStream();
                pivotGridControl1.SaveLayoutToStream(layout, OptionsLayoutBase.FullLayout);

                var rl = new ReportLayout { Id = 0, Name = form.name, Type = ReportLayout.ReportLayoutType.Incoming, Data = layout.ToArray() };
                using (var db = new EFcontext())
                {
                    var contains = db.ReportLayout.Where(o => o.Type == rl.Type && o.Name.Equals(rl.Name, System.StringComparison.OrdinalIgnoreCase)).FirstOrDefault();
                    if (contains != null)
                    {
                        MessageBox.Show("Bunday Hisobot Oldin Kiritilgan!!");
                        return;
                    }
                    db.ReportLayout.Add(rl);
                    db.SaveChanges();
                    Logger.Log("Incoming Report", rl.ToString2());
                    lookUpEdit1.Properties.DataSource = db.ReportLayout.Where(o => o.Type == ReportLayout.ReportLayoutType.Incoming).ToList();
                }
            }
        }

        private void chopetish_Click(object sender, System.EventArgs e)
        {
            pivotGridControl1.ShowRibbonPrintPreview();
        }

        private void lookUpEdit1_EditValueChanged(object sender, System.EventArgs e)
        {
            var reportLayout = (ReportLayout)lookUpEdit1.EditValue;
            pivotGridControl1.RestoreLayoutFromStream(new MemoryStream(reportLayout.Data), OptionsLayoutBase.FullLayout);
        }
        private void ochirish_Click(object sender, System.EventArgs e)
        {

        }
    }
}
